# Generated by Django 5.0.14 on 2026-06-25 19:14

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtapaProductiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('orden', models.IntegerField(unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('tiempo_esperado_horas', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Etapa Productiva',
                'verbose_name_plural': 'Etapas Productivas',
                'db_table': 'etapas_productivas',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('rfc', models.CharField(blank=True, max_length=13, null=True, unique=True)),
                ('direccion', models.TextField(blank=True)),
                ('telefono', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'proveedores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='VariedadTabaco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('caracteristicas', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Variedad de Tabaco',
                'verbose_name_plural': 'Variedades de Tabaco',
                'db_table': 'variedades_tabaco',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='El teléfono debe tener exactamente 10 dígitos', regex='^\\d{10}$')])),
                ('rol', models.CharField(choices=[('administrador', 'Administrador'), ('supervisor', 'Supervisor'), ('operario', 'Operario'), ('control_calidad', 'Control de Calidad')], default='operario', max_length=20)),
                ('departamento', models.CharField(choices=[('produccion', 'Producción'), ('calidad', 'Calidad'), ('recepcion', 'Recepción'), ('clasificacion', 'Clasificación'), ('seleccion', 'Selección'), ('empaque', 'Empaque'), ('distribucion', 'Distribución'), ('administracion', 'Administración')], max_length=20)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuarios',
                'ordering': ['-fecha_creacion'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='InspeccionCalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_calidad', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_inspeccion', 'En Inspección'), ('aprobado', 'Aprobado'), ('aprobado_con_observaciones', 'Aprobado con Observaciones'), ('rechazado', 'Rechazado')], default='pendiente', max_length=30)),
                ('grado_calidad', models.CharField(blank=True, choices=[('A', 'A - Excelente'), ('B', 'B - Bueno'), ('C', 'C - Aceptable'), ('D', 'D - Deficiente')], max_length=1, null=True)),
                ('temperatura', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('humedad', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('peso_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('humedad_correcta', models.BooleanField(default=False)),
                ('temperatura_correcta', models.BooleanField(default=False)),
                ('peso_correcto', models.BooleanField(default=False)),
                ('embalaje_correcto', models.BooleanField(default=False)),
                ('etiquetado_correcto', models.BooleanField(default=False)),
                ('qr_legible', models.BooleanField(default=False)),
                ('qr_verificado', models.BooleanField(default=False)),
                ('decision', models.CharField(blank=True, choices=[('aprobar', 'Aprobar Lote'), ('rechazar', 'Rechazar Lote'), ('solicitar_correccion', 'Solicitar Corrección'), ('solicitar_reinspeccion', 'Solicitar Reinspección')], max_length=30, null=True)),
                ('motivo_rechazo', models.CharField(choices=[('ninguno', 'Ninguno'), ('humedad_excesiva', 'Humedad Excesiva'), ('danos_fisicos', 'Daños Físicos'), ('peso_incorrecto', 'Peso Incorrecto'), ('contaminacion', 'Contaminación'), ('mala_clasificacion', 'Mala Clasificación'), ('otro', 'Otro')], default='ninguno', max_length=30)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_hora_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_hora_fin', models.DateTimeField(blank=True, null=True)),
                ('duracion_minutos', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='data.etapaproductiva')),
                ('inspector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inspección de Calidad',
                'verbose_name_plural': 'Inspecciones de Calidad',
                'db_table': 'inspecciones_calidad',
                'ordering': ['-fecha_hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='EvidenciaCalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('foto', 'Fotografía'), ('documento', 'Documento')], default='foto', max_length=10)),
                ('archivo', models.FileField(upload_to='evidencias/%Y/%m/%d/')),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('inspeccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='data.inspeccioncalidad')),
            ],
            options={
                'verbose_name': 'Evidencia de Calidad',
                'verbose_name_plural': 'Evidencias de Calidad',
                'db_table': 'evidencias_calidad',
                'ordering': ['-fecha_subida'],
            },
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=50, unique=True)),
                ('codigo_qr', models.CharField(blank=True, max_length=100, unique=True)),
                ('origen', models.CharField(max_length=200)),
                ('peso_inicial_kg', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('peso_actual_kg', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('cantidad_bultos', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_espera', 'En Espera'), ('en_produccion', 'En Producción'), ('finalizado', 'Finalizado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('fecha_ingreso', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_inicio_produccion', models.DateTimeField(blank=True, null=True)),
                ('fecha_finalizacion', models.DateTimeField(blank=True, null=True)),
                ('observaciones_iniciales', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes_creados', to=settings.AUTH_USER_MODEL)),
                ('etapa_actual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lotes_en_etapa', to='data.etapaproductiva')),
                ('responsable_actual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes_asignados', to=settings.AUTH_USER_MODEL)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='data.proveedor')),
                ('variedad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='data.variedadtabaco')),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
                'db_table': 'lotes',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AddField(
            model_name='inspeccioncalidad',
            name='lote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspecciones', to='data.lote'),
        ),
        migrations.CreateModel(
            name='EventoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('creacion_lote', 'Creación de Lote'), ('movimiento_etapa', 'Movimiento de Etapa'), ('inspeccion_calidad', 'Inspección de Calidad'), ('cambio_estado_lote', 'Cambio de Estado de Lote'), ('creacion_usuario', 'Creación de Usuario'), ('modificacion_usuario', 'Modificación de Usuario'), ('login', 'Inicio de Sesión'), ('logout', 'Cierre de Sesión'), ('alerta_generada', 'Alerta Generada')], max_length=30)),
                ('descripcion', models.TextField()),
                ('datos_adicionales', models.JSONField(blank=True, null=True)),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='data.lote')),
            ],
            options={
                'verbose_name': 'Evento del Sistema',
                'verbose_name_plural': 'Eventos del Sistema',
                'db_table': 'eventos_sistema',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('retraso', 'Retraso en Etapa'), ('cuello_botella', 'Cuello de Botella'), ('calidad_rechazada', 'Calidad Rechazada'), ('sistema', 'Sistema')], max_length=20)),
                ('severidad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=10)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('resuelta', 'Resuelta'), ('ignorada', 'Ignorada')], default='activa', max_length=10)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('resuelto_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_resueltas', to=settings.AUTH_USER_MODEL)),
                ('etapa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.etapaproductiva')),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='data.lote')),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'db_table': 'alertas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoLote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('inicio', 'Inicio de Etapa'), ('pausa', 'Pausa'), ('reanudacion', 'Reanudación'), ('finalizacion', 'Finalización de Etapa'), ('reasignacion', 'Reasignación')], max_length=20)),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('cantidad_procesada_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('tiempo_trabajo_minutos', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('tiempo_pausa_minutos', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('incidencias', models.CharField(choices=[('ninguna', 'Ninguna'), ('humedad', 'Humedad'), ('danos', 'Daños'), ('retraso', 'Retraso'), ('otro', 'Otro')], default='ninguna', max_length=20)),
                ('motivo_retraso', models.CharField(choices=[('ninguno', 'Ninguno'), ('maquinaria', 'Maquinaria'), ('personal', 'Personal'), ('materia_prima', 'Materia Prima'), ('calidad', 'Calidad'), ('otro', 'Otro')], default='ninguno', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('etapa_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_destino', to='data.etapaproductiva')),
                ('etapa_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_origen', to='data.etapaproductiva')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='data.lote')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento de Lote',
                'verbose_name_plural': 'Movimientos de Lote',
                'db_table': 'movimientos_lote',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='Observacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('general', 'General'), ('alerta', 'Alerta'), ('incidencia', 'Incidencia'), ('nota', 'Nota')], default='general', max_length=15)),
                ('contenido', models.TextField()),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observaciones', to='data.lote')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Observación',
                'verbose_name_plural': 'Observaciones',
                'db_table': 'observaciones',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['rol'], name='usuarios_rol_936bfb_idx'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['departamento'], name='usuarios_departa_f6d128_idx'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['estado'], name='usuarios_estado_7877c9_idx'),
        ),
        migrations.AddIndex(
            model_name='inspeccioncalidad',
            index=models.Index(fields=['lote', '-fecha_hora_inicio'], name='inspeccione_lote_id_16cec6_idx'),
        ),
        migrations.AddIndex(
            model_name='inspeccioncalidad',
            index=models.Index(fields=['estado_calidad'], name='inspeccione_estado__013610_idx'),
        ),
        migrations.AddIndex(
            model_name='eventosistema',
            index=models.Index(fields=['-fecha_hora'], name='eventos_sis_fecha_h_991803_idx'),
        ),
        migrations.AddIndex(
            model_name='eventosistema',
            index=models.Index(fields=['tipo'], name='eventos_sis_tipo_20a624_idx'),
        ),
        migrations.AddIndex(
            model_name='alerta',
            index=models.Index(fields=['estado', '-fecha_creacion'], name='alertas_estado_865633_idx'),
        ),
        migrations.AddIndex(
            model_name='alerta',
            index=models.Index(fields=['tipo'], name='alertas_tipo_5c3804_idx'),
        ),
        migrations.AddIndex(
            model_name='alerta',
            index=models.Index(fields=['severidad'], name='alertas_severid_6b75e5_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientolote',
            index=models.Index(fields=['lote', '-fecha_hora'], name='movimientos_lote_id_e07389_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientolote',
            index=models.Index(fields=['tipo_movimiento'], name='movimientos_tipo_mo_2e10ae_idx'),
        ),
        migrations.AddIndex(
            model_name='observacion',
            index=models.Index(fields=['lote', '-fecha_hora'], name='observacion_lote_id_067dca_idx'),
        ),
        migrations.AddIndex(
            model_name='lote',
            index=models.Index(fields=['codigo'], name='lotes_codigo_caf7ae_idx'),
        ),
        migrations.AddIndex(
            model_name='lote',
            index=models.Index(fields=['estado'], name='lotes_estado_a6768b_idx'),
        ),
        migrations.AddIndex(
            model_name='lote',
            index=models.Index(fields=['etapa_actual'], name='lotes_etapa_a_eaad88_idx'),
        ),
        migrations.AddIndex(
            model_name='lote',
            index=models.Index(fields=['fecha_ingreso'], name='lotes_fecha_i_bdc427_idx'),
        ),
    ]
