# Generated by Django 5.2.15 on 2026-06-30 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_usuario_two_factor_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='reset_password_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='reset_password_code_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
