# Generated by Django 5.2.15 on 2026-07-04 03:41

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_usuario_reset_password_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=100, unique=True)),
                ('valor', models.TextField()),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración del Sistema',
                'verbose_name_plural': 'Configuraciones del Sistema',
                'db_table': 'configuracion_sistema',
                'ordering': ['clave'],
            },
        ),
        migrations.AddField(
            model_name='evidenciacalidad',
            name='mime_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='evidenciacalidad',
            name='nombre_archivo',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='evidenciacalidad',
            name='tamano_bytes',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evidenciacalidad',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidencias_subidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evidenciacalidad',
            name='url_externa',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='lote',
            name='total_tiempo_minutos',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='movimientolote',
            name='duracion_total_minutos',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='movimientolote',
            name='es_retrasado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movimientolote',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimientolote',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimientolote',
            name='fecha_pausa',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimientolote',
            name='fecha_reanudacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='observacion',
            name='etapa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observaciones', to='data.etapaproductiva'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='contacto',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='origen',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='evidenciacalidad',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='evidencias/%Y/%m/%d/'),
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lote_codigo', models.CharField(blank=True, max_length=50)),
                ('tipo', models.CharField(choices=[('info', 'Información'), ('warning', 'Advertencia'), ('critical', 'Crítica')], default='info', max_length=10)),
                ('categoria', models.CharField(choices=[('lot', 'Lote'), ('quality', 'Calidad'), ('user', 'Usuario'), ('alert', 'Alerta'), ('production', 'Producción'), ('admin', 'Administración')], default='alert', max_length=15)),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('url_accion', models.CharField(blank=True, max_length=500)),
                ('leida', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones', to='data.lote')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'db_table': 'notificaciones',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['usuario', '-fecha_creacion'], name='notificacio_usuario_cf1441_idx'), models.Index(fields=['leida'], name='notificacio_leida_8f2b73_idx'), models.Index(fields=['categoria'], name='notificacio_categor_04f9f1_idx')],
            },
        ),
    ]
